# kenzok8 Third-party Repository
# These repositories will be appended to ImageBuilder's repositories.conf

src/gz kenzok8_packages https://op.supes.top/packages/aarch64_cortex-a72
src/gz kenzok8_luci https://op.supes.top/luci
